[2024-10-18T08:47:00.600+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_from_local_to_postgres.extract_data scheduled__2024-10-17T00:00:00+00:00 [queued]>
[2024-10-18T08:47:00.616+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_from_local_to_postgres.extract_data scheduled__2024-10-17T00:00:00+00:00 [queued]>
[2024-10-18T08:47:00.618+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-10-18T08:47:00.640+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): extract_data> on 2024-10-17 00:00:00+00:00
[2024-10-18T08:47:00.648+0000] {standard_task_runner.py:60} INFO - Started process 68 to run task
[2024-10-18T08:47:00.653+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_from_local_to_postgres', 'extract_data', 'scheduled__2024-10-17T00:00:00+00:00', '--job-id', '683', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpgvgwersa']
[2024-10-18T08:47:00.655+0000] {standard_task_runner.py:88} INFO - Job 683: Subtask extract_data
[2024-10-18T08:47:00.724+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_from_local_to_postgres.extract_data scheduled__2024-10-17T00:00:00+00:00 [running]> on host 9c093e78d1a2
[2024-10-18T08:47:00.858+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_from_local_to_postgres' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-17T00:00:00+00:00'
[2024-10-18T08:47:01.035+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-10-18T08:47:01.051+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=etl_from_local_to_postgres, task_id=extract_data, execution_date=20241017T000000, start_date=20241018T084700, end_date=20241018T084701
[2024-10-18T08:47:01.107+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-10-18T08:47:01.148+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
